### ISSUE TITLE
creating new user fails due to incorrect token

### ISSUE THREAD

**Issue by rofl0r** [DF-Wiki/DF-Wiki#10]
the token generated has spaces, backslashes and pluses in it and when i copy and pasted it into the box and clicked submit, i always got the message that the token is wrong.

i would suggest making the token alnum-only so its easier for the user to assure he didnt make an error - and of course fixing the bug that prevents user accounts from being created.

**Comment by lethosor** [comment]
Have you double-checked to make sure the username you're trying to use isn't already in use? (I think you should get a better error message in that case, but it's possible that broke.) Also, you need cookies enabled (but you need those to log in anyway).

Edit: also, the token page is case-sensitive. I was able to create an account just now (LethosorTest10).

**Comment by rofl0r** [comment]
> Have you double-checked to make sure the username you're trying to use isn't already in use?

no, i assumed it would tell me if it was already taken. i tried "foobar".

**Comment by lethosor** [comment]
I get this on the account creation form, but nothing on the token page (which should be easy enough to change):
![image](https://cloud.githubusercontent.com/assets/3719547/21473792/00da00ce-cae4-11e6-8e9d-314719471c66.png)

My other two guesses are mismatched letter case and cookies being disabled. Are either of those possible?

**Comment by rofl0r** [comment]
i get this:
```
Login error
Incorrect or missing confirmation code.
```
i now suspect the account creation page tries to display a google captcha as well? it seems uMatrix filters that out.

**Comment by lethosor** [comment]
Yeah, there's a captcha there too. (Sorry, accidentally closed this on mobile)

**Comment by lethosor** [comment]
Sounds the same as #9 to me
