### ISSUE TITLE
Wiki down, need help?

### ISSUE THREAD

**Issue by Ramblurr** [DF-Wiki/DF-Wiki#11]
The wiki has been down some days now. Is there anything I can do to help? sys admin, donate a server, etc?

**Comment by locriani** [comment]
Thanks for letting me know. I need to spend some time fixing some monitoring scripts that have failed to fire and notify me when the site went down. The issue has been resolved.

**Comment by locriani** [comment]
I have set up a pingdom monitoring account instead of just fixing my scripts. Hopefully that proves more reliable in the future.
