### ISSUE TITLE
Can we move to HTTPS?

### ISSUE THREAD

**Issue by Ramblurr** [DF-Wiki/DF-Wiki#12]
Could we install a TLS cert and switch to HTTPS on the wiki?

There are a lot of reasons to do so, login protection, privacy issues etc, but generally its just good practice in today's modern web.

These days with Lets Encrypt, it's super easy and free to get a SSL certificate. I can help if you need it or have any questions.

**Comment by locriani** [comment]
We currently have an https version of the site set up that redirects back to the HTTP version.

Unfortunately, when we first set up HTTPS on the wiki, we found that it dropped ad revenue from enough to pay for the servers and hosting costs to about $7.30 per month, which won't even pay for a single frontend node. I think it's much better now and wouldn't be opposed to doing a https simultaneous trial again, but I'll need to modify the nginx configs to turn off the redirect, and update our puppet repo to resolve some outstanding issues regarding email sending first.

**Comment by Ramblurr** [comment]
Hm, interesting, that's not good of course. 

How did enabling https affect the ad revenue? Were ads not shown on the HTTPS version? Was it a https enforced trial or were http and https versions live together? Also, was it a drop in traffic that led to a decrease in revenue?

**Comment by uristmcgit** [comment]
At the time (it may still be his way), Google had separate auctions for http and https. Ads shown on https just paid a lot less. Having done a quick search, it looks like the anecdotes out there suggest enabling TLS still causes a hit, but perhaps a smaller one than it did years ago.

-Emily

**Comment by uristmcgit** [comment]
Oh weird, I did not realize that one of my emails was associated with that account. The comment above was mine.

-Emily

**Comment by Emily** [comment]
Ok, trying this again... now that I’ve sorted the emails out...

At the time (it may still be his way), Google had separate auctions for http and https. Ads shown on https just paid a lot less. Having done a quick search, it looks like the anecdotes out there suggest enabling TLS still causes a hit, but perhaps a smaller one than it did years ago.

**Comment by Ramblurr** [comment]
Nice!

> Ok, trying this again...

I still don't see it enabled on the wiki? Or did that not mean you enabled it again ;-)

**Comment by lethosor** [comment]
That meant her comments were showing up under another username.

**Comment by braiam** [comment]
> dwarffortresswiki.org uses an invalid security certificate. The certificate expired on May 1, 2018, 7:59:59 PM GMT-4. The current time is July 22, 2018, 7:15 AM.

Seems that you use a COMODO certificate, time to change to LE?

**Comment by lethosor** [comment]
That certificate is probably from when we briefly tried HTTPS, mentioned above. It shouldn't be in use at all right now.

**Comment by braiam** [comment]
Seems to still be in the rotation. I think for that version of nginx you need to restart the server, not just reloading the configuration. Wait, sorry, was thinking that you removed it.

**Comment by lethosor** [comment]
Are you sure your browser hasn't just cached it somehow? The servers have been rebooted a few times since then.

**Comment by braiam** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=dwarffortresswiki.org&s=96.126.119.57

Doubt it.

**Comment by lethosor** [comment]
That page isn't giving me any useful information ("please wait" for ~3 minutes). You are correct that https://dwarffortresswiki.org/ appears to still be active, but if I bypass the certificate check I get a consistent redirect to http://dwarffortresswiki.org/. That's what the HTTPS site was ultimately set up to do back in 2015, and since it isn't used for anything else, I guess the certificate wasn't renewed. Perhaps we should just retire the HTTPS site for now, until we start using HTTPS again?

**Comment by braiam** [comment]
> Perhaps we should just retire the HTTPS site for now, until we start using HTTPS again?

I was expecting going backwards, moving operations to HTTPS, since AdWords [is pushing their  advertisers to https](https://www.blog.google/products/ads/faster-safer-and-better-ad-experiences/) which was the blocking issue before. I could help devising a migration plan but I would like a valid certificate to make sure everything would work.

**Comment by locriani** [comment]
@braiam It's on the list. We're dealing with a bunch of other tech issues first, after which we'll update the certificate and move to HTTPS only.

Before this we still have to:
- Finish migration / testing of mediawiki to lastest version
- Finish migration / testing of migration of database back to mysql
- Finish migration / testing of migration to Google Cloud from our current hosting provider
- Fix captcha issues
- Fix email services
- Fix some potential logging compliance issues
- Fix HTTPS cert

That's currently in rough priority order atm.

(note: These are being tracked in our internal tracker, not on the public tracker)

**Comment by braiam** [comment]
Great!

If you need help with anything I have a couple of boxes lying around.

**Comment by lethosor** [comment]
Done as part of the great mediawiki upgrade of 2019.
