### ISSUE TITLE
Some of the wiki hosts are not displaying images/showing errors

### ISSUE THREAD

**Issue by pkmnfrk** [DF-Wiki/DF-Wiki#14]
As an example, the D for Dwarf banner can be completely busted, depending on the combination of servers that serve a given page.

You might get: (pulled from [DF2014:Pig_iron](http://dwarffortresswiki.org/index.php/DF2014:Pig_iron)
![image](https://user-images.githubusercontent.com/1333816/40281957-87b6e222-5c35-11e8-8a74-188472cab3ad.png)

Or you might get: (pulled from [DF2014:Dwarf](http://dwarffortresswiki.org/index.php/DF2014:Dwarf)
![image](https://user-images.githubusercontent.com/1333816/40281968-b12f0b2a-5c35-11e8-966c-310d1f0ff39b.png)

The error in the latter screen shot is:
```
Error creating thumbnail: convert: unable to open image `/var/www/dfwiki/images/0/0f/D4Dwarf.png': No such file or directory @ error/blob.c/OpenBlob/2638.
convert: unable to open file `/var/www/dfwiki/images/0/0f/D4Dwarf.png' @ error/png.c/ReadPNGImage/3667.
convert: no images defined `/tmp/transform_4ab1b99a20cb-1.png' @ error/convert.c/ConvertImageCommand/3044
```

This does affect other images too, although I've only seen the D for Dwarf banner show the error; other images just show up as broken or missing.

**Comment by locriani** [comment]
NFS must have gone down on one of the nodes. I'll fix it right now.

**Comment by locriani** [comment]
Fixed.

**Comment by pkmnfrk** [comment]
Neat, thanks for the quick response!

**Comment by locriani** [comment]
Thanks for pointing it out!
