### ISSUE TITLE
SVG rendering issues

### ISSUE THREAD

**Issue by lethosor** [DF-Wiki/DF-Wiki#6]
For example, [this svg](http://dwarffortresswiki.org/index.php/File:Translation_Icon.svg) isn't rendering due to what looks like an ImageMagick issue.
(Originally reported [here](http://dwarffortresswiki.org/index.php/Dwarf_Fortress_Wiki_talk:Centralized_Discussion#.SVG_problems.3F))

**Comment by locriani** [comment]
probably missing the svg libs. I'll investigate shortly

**Comment by locriani** [comment]
@Emily Need to add this package to the puppet config: librsvg2-bin

**Comment by locriani** [comment]
@lethosor Fixed. Certain images may be cached on the pages but a purge action will fix them.
