### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by lethosor** [DF-Wiki/DF-Wiki#7]
It's not clear if the next version is save-compatible or not, so we'll need to be able to migrate pages fairly quickly if it isn't (does anyone still have a bot available?). It may be worthwhile to disable editing for non-admins temporarily while that happens.

We'll probably want to rename the DF2014 namespace in either case, to v0.40 or v0.4x (whatever the new version number is). I've been working on templates to make namespace changes a little easier to deal with, so what do you think about renaming DF2014 to v0.40 now?

@DF-Wiki/core

**Comment by Emily** [comment]
@quietust is the one who usually does the runs the bot to migrate pages. If he's not around or available @locriani or I could probably throw something together.

As for renaming, unless there's a good reason to pre-emptively do the rename, I'd prefer to wait. Namespace renaming is always a bit hard on the wiki so I'd rather rename once than twice.

**Comment by lethosor** [comment]
Locriani set up a bot last time, I think. Waiting on renaming is fine with me - it's a little late to address the "DF2014 in 2015" confusion, and renaming it preemptively would be confusing if the release is delayed.

We should also figure out what we want to name the namespace for the new version (whether it's the current DF2014 or a new namespace). I'm leaning a bit towards v0.4x (e.g. v0.41/v0.42) myself, since neither DF2015 or DF2016 would fit it well (or seem to be widely-used) and keeping DF2014/v0.40 would be more confusing.

**Comment by lethosor** [comment]
I set up a poll [here](https://docs.google.com/forms/d/1SG1atLYyK79BqUMVz6pH2R1Pur1XkAAiRFWgeBI_Xz4/viewform).

**Comment by lethosor** [comment]
Looks like v0.4x is the second choice after DF2016. Unless the release gets significantly delayed (it's scheduled for Dec 1 now), I'd still rather go with v0.4x so we don't have confused new players for a month.

**Comment by Emily** [comment]
What about "Current Version" or "Newest Version"?

**Comment by lethosor** [comment]
There were a couple reasons against it in the last release - from what I remember, it would make version-specific categories and templates harder to maintain. There's also the issue of confusion about what version a page refers to when there's a migration in progress.
I'd certainly like to find a more obvious way to indicate that a page is for the current version, though, if the {{av}} box isn't enough (and apparently it isn't for some people, since I've seen a few people posting v0.34 links thinking they're current in 2015). We could adopt a fixed-position/floating version chooser (a la Django/ReadTheDocs), or a banner of some kind (for old-version pages?), or something else entirely. Thoughts?

**Comment by lethosor** [comment]
@DF-Wiki/core 
Speaking of migration: I'm not sure if you've seen what Toady had to say about save compatibility, but it sounds like they'll be compatible (or at least any compatibility breaks aren't intentional on his part, which means DF v0.4x will at least recognize new saves and he'll hopefully fix problems that arise). He did mention in a FotF post that some new features won't work in old saves, but given that we've had similar situations before and not made a new namespace (e.g. gelding in 0.40.19, although that was admittedly a small addition), I don't personally feel that creating a new namespace is necessary. One possibility could be making a template similar {{old}} for articles that are exclusive to the new version.

**Comment by locriani** [comment]
I think we're ok as is here. Going to close this issue.
