### ISSUE TITLE
HTML and display Issues with page http://dwarffortresswiki.org/index.php/DF2014:General

### ISSUE THREAD

**Issue by ghost** [DF-Wiki/DF-Wiki#8]
The page Layout and styling for http://dwarffortresswiki.org/index.php/DF2014:General is broken, it does not display the current content  of the page but a older version (the version displayed has the migration template but the current content does not). 
The display of the correct page can be forced by adding a query parameter to the url like http://dwarffortresswiki.org/index.php/DF2014:General?test=foo. The 2 links return different html code, difference can be seen here https://www.diffnow.com/?report=ylzkx

This appears to be  a issue caused by either the wiki software or the server returning a cached page

**Comment by lethosor** [comment]
[This template](http://dwarffortresswiki.org/index.php/Template:Migrated_article)? I'm not seeing it, so it could be cached, but I'd be surprised if that's still cached somewhere. It looks like it was removed about 2 years ago.

**Comment by ghost** [comment]
Here is a screenshot of how the http://dwarffortresswiki.org/index.php/DF2014:General page looks 
![screencapture-dwarffortresswiki-org-index-php-df2014-general-1481205541957](https://cloud.githubusercontent.com/assets/6429269/21012604/854f7dda-bd5f-11e6-9e86-92446a40fd7f.png)

And here is how the page looks if i add a query string http://dwarffortresswiki.org/index.php/DF2014:General?test=foo 
![screencapture-dwarffortresswiki-org-index-php-df2014-general-1481205728750](https://cloud.githubusercontent.com/assets/6429269/21012654/ba4c9a86-bd5f-11e6-80ea-48e3cae11541.png)

PS. I am not logged in

**Comment by lethosor** [comment]
Yeah, the caching probably has something to do with you not being logged in. I tried purging that page from the cache, so can you check again and see if the first link works?

**Comment by ghost** [comment]
I tried the link again and it now works properly. Clearing the cache solved the issue.

**Comment by lethosor** [comment]
If you're curious, you ought to be able to do what I did by adding `?action=purge` to the URL, although I believe it will prompt you before actually clearing that page from the cache. Feel free to let us know if you find others like this.

@locriani any idea what happened here?

**Comment by locriani** [comment]
Looks like a css file didn't get loaded for some reason. No repro so closing this issue.
