### ISSUE TITLE
security question for anonymous edits doesnt show up

### ISSUE THREAD

**Issue by rofl0r** [DF-Wiki/DF-Wiki#9]
i wanted to edit the chunk in http://dwarffortresswiki.org/index.php?title=DF2014:Graphics_set_repository related to mayday . clicked on edit, changed the text, checked preview, then clicked on save, and there was a message that i would have to enter text from a box shown below but there was no box, and no place to enter the answer.

**Comment by lethosor** [comment]
I was able to get the captcha to show up when I was logged out. I think Google is discontinuing the API we're using in the near future, though, so it would be a good idea to switch to something else.

**Comment by rofl0r** [comment]
oh, that is from an external service ? in that case ublock or umatrix might have interfered.

**Comment by lethosor** [comment]
It works for me with uBlock, but I'm not sure if uMatrix could interfere. It's a pretty typical captcha (albeit old), so I'd expect blockers to be able to avoid blocking it, but if you've configured yours to block anything Google-related or something, that could explain it.

**Comment by rofl0r** [comment]
yeah, i got uMatrix on default settings, and it blocks any third-party iframes etc.
i am still rather new to it so it didn't strike me as obvious that uMatrix filtered something out.
